version: "3.8"

services:
  minecraft-server:
    image: itzg/minecraft-server:java8-graalvm-ce
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      MEMORY: "2G"
      TYPE: "PURPUR"
      VERSION: "1.16.5"
      MOTD: "Revivan el server"
      ICON: "https://www.myinstants.com/media/instants_images/revivan-el-server-homero.png"
      DIFFICULTY: "hard"
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data